package com.realistikosu.osu;

public enum PacketId {
    OSU_CHANGE_ACTION((short) 0),
    OSU_SEND_PUBLIC_MESSAGE((short) 1),
    OSU_LOGOUT((short) 2),
    OSU_REQUEST_STATUS_UPDATE((short) 3),
    OSU_HEARTBEAT((short) 4),
    SRV_LOGIN_REPLY((short) 5),
    SRV_SEND_MESSAGE((short) 7),
    SRV_HEARTBEAT((short) 8),
    SRV_USER_STATS((short) 11),
    SRV_USER_LOGOUT((short) 12),
    SRV_SPECTATOR_JOINED((short) 13),
    SRV_SPECTATOR_LEFT((short) 14),
    SRV_SPECTATE_FRAMES((short) 15),
    OSU_START_SPECTATING((short) 16),
    OSU_STOP_SPECTATING((short) 17),
    OSU_SPECTATE_FRAMES((short) 18),
    SRV_VERSION_UPDATE((short) 19),
    OSU_ERROR_REPORT((short) 20),
    OSU_CANT_SPECTATE((short) 21),
    SRV_SPECTATOR_CANT_SPECTATE((short) 22),
    SRV_GET_ATTENTION((short) 23),
    SRV_NOTIFICATION((short) 24),
    OSU_SEND_PRIVATE_MESSAGE((short) 25),
    SRV_UPDATE_MATCH((short) 26),
    SRV_NEW_MATCH((short) 27),
    SRV_DISPOSE_MATCH((short) 28),
    OSU_PART_LOBBY((short) 29),
    OSU_JOIN_LOBBY((short) 30),
    OSU_CREATE_MATCH((short) 31),
    OSU_JOIN_MATCH((short) 32),
    OSU_PART_MATCH((short) 33),
    SRV_TOGGLE_BLOCK_NON_FRIEND_DMS((short) 34),
    SRV_MATCH_JOIN_SUCCESS((short) 36),
    SRV_MATCH_JOIN_FAIL((short) 37),
    OSU_MATCH_CHANGE_SLOT((short) 38),
    OSU_MATCH_READY((short) 39),
    OSU_MATCH_LOCK((short) 40),
    OSU_MATCH_CHANGE_SETTINGS((short) 41),
    SRV_FELLOW_SPECTATOR_JOINED((short) 42),
    SRV_FELLOW_SPECTATOR_LEFT((short) 43),
    OSU_MATCH_START((short) 44),
    SRV_ALL_PLAYERS_LOADED((short) 45),
    SRV_MATCH_START((short) 46),
    OSU_MATCH_SCORE_UPDATE((short) 47),
    SRV_MATCH_SCORE_UPDATE((short) 48),
    OSU_MATCH_COMPLETE((short) 49),
    SRV_MATCH_TRANSFER_HOST((short) 50),
    OSU_MATCH_CHANGE_MODS((short) 51),
    OSU_MATCH_LOAD_COMPLETE((short) 52),
    SRV_MATCH_ALL_PLAYERS_LOADED((short) 53),
    OSU_MATCH_NO_BEATMAP((short) 54),
    OSU_MATCH_UNREADY((short) 55),
    OSU_MATCH_FAILED((short) 56),
    SRV_MATCH_PLAYER_FAILED((short) 57),
    SRV_MATCH_COMPLETE((short) 58),
    OSU_MATCH_HAS_BEATMAP((short) 59),
    OSU_MATCH_SKIP_REQUEST((short) 60),
    SRV_MATCH_SKIP((short) 61),
    OSU_CHANNEL_JOIN((short) 63),
    SRV_CHANNEL_JOIN_SUCCESS((short) 64),
    SRV_CHANNEL_INFO((short) 65),
    SRV_CHANNEL_KICK((short) 66),
    SRV_CHANNEL_AUTO_JOIN((short) 67),
    OSU_BEATMAP_INFO_REQUEST((short) 68),
    SRV_BEATMAP_INFO_REPLY((short) 69),
    OSU_MATCH_TRANSFER_HOST_2((short) 70),
    SRV_PRIVILEGES((short) 71),
    SRV_FRIENDS_LIST((short) 72),
    OSU_FRIEND_ADD((short) 73),
    OSU_FRIEND_REMOVE((short) 74),
    SRV_PROTOCOL_VERSION((short) 75),
    SRV_MAIN_MENU_ICON((short) 76),
    OSU_MATCH_CHANGE_TEAM((short) 77),
    OSU_CHANNEL_PART((short) 78),
    OSU_RECEIVE_UPDATES((short) 79),
    SRV_MATCH_PLAYER_SKIPPED((short) 81),
    OSU_SET_AWAY_MESSAGE((short) 82),
    SRV_USER_PRESENCE((short) 83),
    OSU_USER_STATS_REQUEST((short) 85),
    SRV_RESTART((short) 86),
    OSU_MATCH_INVITE((short) 87),
    SRV_MATCH_INVITE((short) 88),
    SRV_CHANNEL_INFO_END((short) 89),
    OSU_MATCH_CHANGE_PASSWORD((short) 90),
    SRV_MATCH_CHANGE_PASSWORD((short) 91),
    SRV_SILENCE_END((short) 92),
    OSU_TOURNAMENT_MATCH_INFO_REQUEST((short) 93),
    SRV_USER_SILENCED((short) 94),
    SRV_USER_PRESENCE_SINGLE((short) 95),
    SRV_USER_PRESENCE_BUNDLE((short) 96),
    OSU_USER_PRESENCE_REQUEST((short) 97),
    OSU_USER_PRESENCE_REQUEST_ALL((short) 98),
    OSU_TOGGLE_BLOCK_NON_FRIEND_DMS((short) 99),
    SRV_USER_DM_BLOCKED((short) 100),
    SRV_TARGET_IS_SILENCED((short) 101),
    SRV_VERSION_UPDATE_FORCED((short) 102),
    SRV_SWITCH_SERVER((short) 103),
    SRV_ACCOUNT_RESTRICTED((short) 104),
    SRV_RTX((short) 105),
    SRV_MATCH_ABORT((short) 106),
    SRV_SWITCH_TOURNAMENT_SERVER((short) 107),
    OSU_TOURNAMENT_JOIN_MATCH_CHANNEL((short) 108),
    OSU_TOURNAMENT_LEAVE_MATCH_CHANNEL((short) 109);

    private final short value;

    PacketId(short value) {
        this.value = value;
    }

    public short getValue() {
        return value;
    }
}

